name: Deploy static content to Pages

on:
  schedule:
    - cron: "0 0,3 * * *"

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run Python Script
        env:
          BAKA_USERNAME: ${{ secrets.USERNAME }}
          BAKA_PASSWORD: ${{ secrets.PASSWORD }}
          SCHOOL_DATA: ${{ secrets.DATA }}
        run: uv run light-autobaka

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./index.html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
